#!/usr/bin/python3 

import qrcode

data = ''   #which ever data you wish to encode

qr = qrcode.QRcode(version = 1, box_size=10, border=5)      #adjusting the size if the qrcode

qr.add_data(data)

qr.make(fit=True)
img = qr.make_image(fill_color='blue', back_colour='white')   #editing the colours of the QRcode

img.save('')      #choose file path location to save your QR-Code image

